/*
 * o2cb_err.c:
 * This file is automatically generated; please do not edit it.
 */

#include <stdlib.h>

#define N_(a) a

static const char * const text[] = {
	N_(	"Invalid name for a cluster"),
	N_(	"Memory allocation failed"),
	N_(	"I/O error on channel"),
	N_(	"Unable to access cluster service"),
	N_(	"Internal logic failure"),
	N_(	"Insufficient permissions to access cluster service"),
	N_(	"Cluster already exists"),
	N_(	"Node already exists"),
	N_(	"Heartbeat region already exists"),
	N_(	"Heartbeat region in use"),
	N_(	"Block size is invalid"),
	N_(	"Block count is invalid"),
	N_(	"Could not determine local host name"),
	N_(	"Configuration error discovered"),
	N_(	"Node number is invalid"),
	N_(	"Node manager kernel module is not loaded"),
	N_(	"Could not access heartbeat region semaphore set"),
	N_(	"Region semaphore set destroyed"),
	N_(	"Revision of OCFS2-Tools is out of date."),
	N_(        "Cluster stack specified does not match the one currently running"),
    0
};

struct error_table {
    char const * const * msgs;
    long base;
    int n_msgs;
};
struct et_list {
    struct et_list *next;
    const struct error_table * table;
};
extern struct et_list *_et_list;

const struct error_table et_o2cb_error_table = { text, -1485349888L, 20 };

static struct et_list link = { 0, 0 };

void initialize_o2cb_error_table_r(struct et_list **list);
void initialize_o2cb_error_table(void);

void initialize_o2cb_error_table(void) {
    initialize_o2cb_error_table_r(&_et_list);
}

/* For Heimdal compatibility */
void initialize_o2cb_error_table_r(struct et_list **list)
{
    struct et_list *et, **end;

    for (end = list, et = *list; et; end = &et->next, et = et->next)
        if (et->table->msgs == text)
            return;
    et = malloc(sizeof(struct et_list));
    if (et == 0) {
        if (!link.table)
            et = &link;
        else
            return;
    }
    et->table = &et_o2cb_error_table;
    et->next = 0;
    *end = et;
}
