/*
 * o2cb_err.h:
 * This file is automatically generated; please do not edit it.
 */

#include <et/com_err.h>

#define O2CB_ET_INVALID_CLUSTER_NAME             (-1485349888L)
#define O2CB_ET_NO_MEMORY                        (-1485349887L)
#define O2CB_ET_IO                               (-1485349886L)
#define O2CB_ET_SERVICE_UNAVAILABLE              (-1485349885L)
#define O2CB_ET_INTERNAL_FAILURE                 (-1485349884L)
#define O2CB_ET_PERMISSION_DENIED                (-1485349883L)
#define O2CB_ET_CLUSTER_EXISTS                   (-1485349882L)
#define O2CB_ET_NODE_EXISTS                      (-1485349881L)
#define O2CB_ET_REGION_EXISTS                    (-1485349880L)
#define O2CB_ET_REGION_IN_USE                    (-1485349879L)
#define O2CB_ET_INVALID_BLOCK_SIZE               (-1485349878L)
#define O2CB_ET_INVALID_BLOCK_COUNT              (-1485349877L)
#define O2CB_ET_HOSTNAME_UNKNOWN                 (-1485349876L)
#define O2CB_ET_CONFIGURATION_ERROR              (-1485349875L)
#define O2CB_ET_INVALID_NODE_NUM                 (-1485349874L)
#define O2CB_ET_MODULE_NOT_LOADED                (-1485349873L)
#define O2CB_ET_BAD_SEM                          (-1485349872L)
#define O2CB_ET_NO_SEM                           (-1485349871L)
#define O2CB_ET_BAD_VERSION                      (-1485349870L)
#define O2CB_ET_INVALID_STACK_NAME               (-1485349869L)
extern const struct error_table et_o2cb_error_table;
extern void initialize_o2cb_error_table(void);

/* For compatibility with Heimdal */
extern void initialize_o2cb_error_table_r(struct et_list **list);

#define ERROR_TABLE_BASE_o2cb (-1485349888L)

/* for compatibility with older versions... */
#define init_o2cb_err_tbl initialize_o2cb_error_table
#define o2cb_err_base ERROR_TABLE_BASE_o2cb
