/*
 * ocfs2_err.h:
 * This file is automatically generated; please do not edit it.
 */

#include <et/com_err.h>

#define OCFS2_ET_NAMED_DEVICE_NOT_FOUND          (-1512559360L)
#define OCFS2_ET_BAD_DEVICE_NAME                 (-1512559359L)
#define OCFS2_ET_IO                              (-1512559358L)
#define OCFS2_ET_SHORT_READ                      (-1512559357L)
#define OCFS2_ET_SHORT_WRITE                     (-1512559356L)
#define OCFS2_ET_NO_MEMORY                       (-1512559355L)
#define OCFS2_ET_INVALID_ARGUMENT                (-1512559354L)
#define OCFS2_ET_OCFS_REV                        (-1512559353L)
#define OCFS2_ET_BAD_MAGIC                       (-1512559352L)
#define OCFS2_ET_UNEXPECTED_BLOCK_SIZE           (-1512559351L)
#define OCFS2_ET_CORRUPT_SUPERBLOCK              (-1512559350L)
#define OCFS2_ET_UNSUPP_FEATURE                  (-1512559349L)
#define OCFS2_ET_RO_UNSUPP_FEATURE               (-1512559348L)
#define OCFS2_ET_CONFLICTING_FEATURES            (-1512559347L)
#define OCFS2_ET_BAD_INODE_MAGIC                 (-1512559346L)
#define OCFS2_ET_BAD_BLKNO                       (-1512559345L)
#define OCFS2_ET_RO_FILESYS                      (-1512559344L)
#define OCFS2_ET_JOURNAL_TOO_SMALL               (-1512559343L)
#define OCFS2_ET_BAD_JOURNAL_SUPERBLOCK_MAGIC    (-1512559342L)
#define OCFS2_ET_BAD_JOURNAL_REVOKE              (-1512559341L)
#define OCFS2_ET_BAD_JOURNAL_TAG                 (-1512559340L)
#define OCFS2_ET_INODE_NOT_VALID                 (-1512559339L)
#define OCFS2_ET_INODE_CANNOT_BE_ITERATED        (-1512559338L)
#define OCFS2_ET_BAD_EXTENT_BLOCK_MAGIC          (-1512559337L)
#define OCFS2_ET_CORRUPT_EXTENT_BLOCK            (-1512559336L)
#define OCFS2_ET_DIR_CORRUPTED                   (-1512559335L)
#define OCFS2_ET_NO_DIRECTORY                    (-1512559334L)
#define OCFS2_ET_DIRENT_NOT_FOUND                (-1512559333L)
#define OCFS2_ET_FILE_NOT_FOUND                  (-1512559332L)
#define OCFS2_ET_DIR_NO_SPACE                    (-1512559331L)
#define OCFS2_ET_INVALID_BIT                     (-1512559330L)
#define OCFS2_ET_INTERNAL_FAILURE                (-1512559329L)
#define OCFS2_ET_BAD_GROUP_DESC_MAGIC            (-1512559328L)
#define OCFS2_ET_CORRUPT_GROUP_DESC              (-1512559327L)
#define OCFS2_ET_CORRUPT_CHAIN                   (-1512559326L)
#define OCFS2_ET_INVALID_EXTENT_LOOKUP           (-1512559325L)
#define OCFS2_ET_EXTENT_NOT_FOUND                (-1512559324L)
#define OCFS2_ET_DUPLICATE_BLOCK                 (-1512559323L)
#define OCFS2_ET_BIT_NOT_FOUND                   (-1512559322L)
#define OCFS2_ET_FREEING_UNALLOCATED_REGION      (-1512559321L)
#define OCFS2_ET_EXPAND_DIR_ERR                  (-1512559320L)
#define OCFS2_ET_NO_SPACE                        (-1512559319L)
#define OCFS2_ET_ITERATION_COMPLETE              (-1512559318L)
#define OCFS2_ET_SYMLINK_LOOP                    (-1512559317L)
#define OCFS2_ET_BAD_HEARTBEAT_FILE              (-1512559316L)
#define OCFS2_ET_UNKNOWN_FILESYSTEM              (-1512559315L)
#define OCFS2_ET_BLOCK_SIZE_TOO_SMALL_FOR_HARDWARE (-1512559314L)
#define OCFS2_ET_INVALID_LOCKRES                 (-1512559313L)
#define OCFS2_ET_NO_IONICE                       (-1512559312L)
#define OCFS2_ET_NO_BACKUP_SUPER                 (-1512559311L)
#define OCFS2_ET_TOO_MANY_SLOTS                  (-1512559310L)
#define OCFS2_ET_CANNOT_INLINE_DATA              (-1512559309L)
#define OCFS2_ET_BAD_DIR_BLOCK_MAGIC             (-1512559308L)
#define OCFS2_ET_BAD_XATTR_BLOCK_MAGIC           (-1512559307L)
#define OCFS2_ET_UNKNOWN_FEATURE                 (-1512559306L)
#define OCFS2_ET_CORRUPT_QUOTA_FILE              (-1512559305L)
#define OCFS2_ET_CANNOT_DETERMINE_SECTOR_SIZE    (-1512559304L)
#define OCFS2_ET_DX_BALANCE_EMPTY_LEAF           (-1512559303L)
#define OCFS2_ET_NONEMTY_QUOTA_HASH              (-1512559302L)
extern const struct error_table et_ocfs_error_table;
extern void initialize_ocfs_error_table(void);

/* For compatibility with Heimdal */
extern void initialize_ocfs_error_table_r(struct et_list **list);

#define ERROR_TABLE_BASE_ocfs (-1512559360L)

/* for compatibility with older versions... */
#define init_ocfs_err_tbl initialize_ocfs_error_table
#define ocfs_err_base ERROR_TABLE_BASE_ocfs
