/*
 * o2ne_err.h:
 * This file is automatically generated; please do not edit it.
 */

#include <et/com_err.h>

#define TUNEFS_ET_SIGNALS_FAILED                 (-1485168896L)
#define TUNEFS_ET_HEARTBEAT_DEV                  (-1485168895L)
#define TUNEFS_ET_RESIZE_IN_PROGRESS             (-1485168894L)
#define TUNEFS_ET_TUNEFS_IN_PROGRESS             (-1485168893L)
#define TUNEFS_ET_INVALID_STACK_NAME             (-1485168892L)
#define TUNEFS_ET_PERFORM_ONLINE                 (-1485168891L)
#define TUNEFS_ET_DEVICE_BUSY                    (-1485168890L)
#define TUNEFS_ET_NOT_MOUNTED                    (-1485168889L)
#define TUNEFS_ET_ONLINE_FAILED                  (-1485168888L)
#define TUNEFS_ET_INTERNAL_FAILURE               (-1485168887L)
#define TUNEFS_ET_NO_MEMORY                      (-1485168886L)
#define TUNEFS_ET_JOURNAL_DIRTY                  (-1485168885L)
#define TUNEFS_ET_INVALID_NUMBER                 (-1485168884L)
#define TUNEFS_ET_TOO_MANY_SLOTS_OLD             (-1485168883L)
#define TUNEFS_ET_TOO_MANY_SLOTS_EXTENDED        (-1485168882L)
#define TUNEFS_ET_ORPHAN_DIR_NOT_EMPTY           (-1485168881L)
#define TUNEFS_ET_TRUNCATE_LOG_NOT_EMPTY         (-1485168880L)
#define TUNEFS_ET_LOCAL_ALLOC_NOT_EMPTY          (-1485168879L)
#define TUNEFS_ET_UNWRITTEN_PRESENT              (-1485168878L)
#define TUNEFS_ET_SPARSE_MISSING                 (-1485168877L)
#define TUNEFS_ET_OPERATION_FAILED               (-1485168876L)
#define TUNEFS_ET_ONLINE_NOT_SUPPORTED           (-1485168875L)
#define TUNEFS_ET_CLUSTER_SKIPPED                (-1485168874L)
#define TUNEFS_ET_DX_DIRS_SCAN_FAILED            (-1485168873L)
#define TUNEFS_ET_IO_WRITE_FAILED                (-1485168872L)
#define TUNEFS_ET_DX_DIRS_TRUNCATE_FAILED        (-1485168871L)
#define TUNEFS_ET_DX_DIRS_BUILD_FAILED           (-1485168870L)
#define TUNEFS_ET_INSTALL_DIR_TRAILER_FAILED     (-1485168869L)
extern const struct error_table et_o2ne_error_table;
extern void initialize_o2ne_error_table(void);

/* For compatibility with Heimdal */
extern void initialize_o2ne_error_table_r(struct et_list **list);

#define ERROR_TABLE_BASE_o2ne (-1485168896L)

/* for compatibility with older versions... */
#define init_o2ne_err_tbl initialize_o2ne_error_table
#define o2ne_err_base ERROR_TABLE_BASE_o2ne
