/*
 * o2dlm_err.h:
 * This file is automatically generated; please do not edit it.
 */

#include <et/com_err.h>

#define O2DLM_ET_NO_MEMORY                       (-1485330944L)
#define O2DLM_ET_SERVICE_UNAVAILABLE             (-1485330943L)
#define O2DLM_ET_INVALID_LOCK_NAME               (-1485330942L)
#define O2DLM_ET_INVALID_LOCK_LEVEL              (-1485330941L)
#define O2DLM_ET_INTERNAL_FAILURE                (-1485330940L)
#define O2DLM_ET_NAME_TOO_LONG                   (-1485330939L)
#define O2DLM_ET_STATFS                          (-1485330938L)
#define O2DLM_ET_NO_FS_DIR                       (-1485330937L)
#define O2DLM_ET_NO_FS                           (-1485330936L)
#define O2DLM_ET_OPEN_DLM_DIR                    (-1485330935L)
#define O2DLM_ET_NO_DOMAIN_DIR                   (-1485330934L)
#define O2DLM_ET_BAD_DOMAIN_DIR                  (-1485330933L)
#define O2DLM_ET_BUSY_DOMAIN_DIR                 (-1485330932L)
#define O2DLM_ET_DOMAIN_DIR                      (-1485330931L)
#define O2DLM_ET_DOMAIN_DESTROY                  (-1485330930L)
#define O2DLM_ET_DOMAIN_CREATE                   (-1485330929L)
#define O2DLM_ET_RANDOM                          (-1485330928L)
#define O2DLM_ET_BUSY_LOCK                       (-1485330927L)
#define O2DLM_ET_OUTPUT_ERROR                    (-1485330926L)
#define O2DLM_ET_UNLINK                          (-1485330925L)
#define O2DLM_ET_UNKNOWN_LOCK                    (-1485330924L)
#define O2DLM_ET_RECURSIVE_LOCK                  (-1485330923L)
#define O2DLM_ET_LOCKING                         (-1485330922L)
#define O2DLM_ET_FAILED_UNLOCKS                  (-1485330921L)
#define O2DLM_ET_INVALID_ARGS                    (-1485330920L)
#define O2DLM_ET_TRYLOCK_FAILED                  (-1485330919L)
#define O2DLM_ET_LVB_READ                        (-1485330918L)
#define O2DLM_ET_LVB_WRITE                       (-1485330917L)
#define O2DLM_ET_SEEK                            (-1485330916L)
#define O2DLM_ET_DOMAIN_BUSY                     (-1485330915L)
#define O2DLM_ET_BAST_UNSUPPORTED                (-1485330914L)
#define O2DLM_ET_LVB_INVALID                     (-1485330913L)
extern const struct error_table et_o2dl_error_table;
extern void initialize_o2dl_error_table(void);

/* For compatibility with Heimdal */
extern void initialize_o2dl_error_table_r(struct et_list **list);

#define ERROR_TABLE_BASE_o2dl (-1485330944L)

/* for compatibility with older versions... */
#define init_o2dl_err_tbl initialize_o2dl_error_table
#define o2dl_err_base ERROR_TABLE_BASE_o2dl
